version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - "8086:8086"

  db:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 30s
      interval: 10s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portifolio
    ports:
      - "5432:5432"
